### ISSUE TITLE
How to access the custom arguments?

### ISSUE THREAD

**Issue by creadicted** [xiezi5160/MultirunForGodot4#1]
Hey! Thank you for the GD4 update. How would you access the custom arguments?

**Comment by cyraid** [comment]
@creadicted You can do `++ listen arg2 arg3` as arguments for the first window, and `++ join arg2` to the other windows, and access them with C#:
```csharp
OS.GetCmdlineUserArgs()
```
or with GDScript:
```gdscript
OS.get_cmdline_user_args()
```
