### ISSUE TITLE
no work 4.1

### ISSUE THREAD

**Issue by zipfriis** [xiezi5160/MultirunForGodot4#2]
fix please, pretty please. I need this badly or i am gonna off my self

**Comment by cyraid** [comment]
Hi @zipfriis don't off yourself! You can try my fork of this repo that adds custom arguments and also removes the window distance (as you can specify custom arguments per window).

https://github.com/cyraid/MultirunForGodot4

@xiezi5160 Let me know if you'd be interested in me making a pull request for yours?

**Comment by xiezi5160** [comment]
> Hi @zipfriis don't off yourself! You can try my fork of this repo that adds custom arguments and also removes the window distance (as you can specify custom arguments per window).
> 
> https://github.com/cyraid/MultirunForGodot4
> 
> @xiezi5160 Let me know if you'd be interested in me making a pull request for yours?

@cyraid Thank you for helping me deal with the feedback from my friends!

I found that 4.x has multi-window running function, so there is no maintenance, if you are interested, you can continue to maintain this plug-in, thank you!

**Comment by cyraid** [comment]
@xiezi5160 You're welcome! I should be able to help out as a maintainer. :) I removed the window distancing support as I added ability to specify custom arguments to each window, so now people can do --position themselves etc. Would you be okay with the change? There's talks of adding custom argument support per window in godot proposals but I found that there's been slow movement and your plugin did a lot of it already, so I just added the changes. Let me know :)

**Comment by xiezi5160** [comment]
Please, as long as you are happy ~
&nbsp;


冰糖葫芦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dennis ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiezi5160/MultirunForGodot4] no work 4.1 (Issue #2)





 
@xiezi5160 You're welcome! I should be able to help out as a maintainer. :) I removed the window distancing support as I added ability to specify custom arguments to each window, so now people can do --position themselves etc. Would you be okay with the change? There's talks of adding custom argument support per window in godot proposals but I found that there's been slow movement and your plugin did a lot of it already, so I just added the changes. Let me know :)

**Comment by cyraid** [comment]
@xiezi5160 okay! If you'd like feel free to add me as a collaborator if you like and I'll push the changes and work on this repo! :)

**Comment by xiezi5160** [comment]
> @xiezi5160 okay! If you'd like feel free to add me as a collaborator if you like and I'll push the changes and work on this repo! :)

Yes, I have already invited you. Thank you for your efforts~ 👍
