### ISSUE TITLE
Update asset library.

### ISSUE THREAD

**Issue by cyraid** [xiezi5160/MultirunForGodot4#4]
@xiezi5160 Not sure how to contact you lol, but I was wondering if you could bump the godot asset library? (https://godotengine.org/asset-library/asset/2054) That it's version 2.0.2? The asset library site should implement other people to update haha

**Comment by xiezi5160** [comment]
> @xiezi5160 Not sure how to contact you lol, but I was wondering if you could bump the godot asset library? (https://godotengine.org/asset-library/asset/2054) That it's version 2.0.2? The asset library site should implement other people to update haha

@cyraid Okay, let me update, the plug -in store does not seem to set up multiple developers. If you know how to set up, please tell me.

**Comment by cyraid** [comment]
@xiezi5160 It doesn't seem possible to have multiple collaborators as far as I'm aware, but I have made a request on their github for the site. :)

**Comment by xiezi5160** [comment]
> @xiezi5160 It doesn't seem possible to have multiple collaborators as far as I'm aware, but I have made a request on their github for the site. :)

I have submitted the version you pushed to the Godot Asset Library, and the current status is, waiting for their review.
![image](https://github.com/xiezi5160/MultirunForGodot4/assets/5836822/a288cd98-3cb4-472c-b3a6-ec108067b476)

**Comment by xiezi5160** [comment]
![image](https://github.com/xiezi5160/MultirunForGodot4/assets/5836822/35af3123-e684-4574-a527-ee172be28dcd)
