### ISSUE TITLE
Does not work with 4.2 Beta 1

### ISSUE THREAD

**Issue by zolrath** [xiezi5160/MultirunForGodot4#5]
Hello!
This is about as early as I can report an incompatibility but installing this and activating the plugin on Godot 4.2 beta 1 doesn't add the new buttons or menu into the project.

Really glad this plugin exists, would love for this to get rolled into Godot 4.3!

**Comment by xiezi5160** [comment]
> Hello! This is about as early as I can report an incompatibility but installing this and activating the plugin on Godot 4.2 beta 1 doesn't add the new buttons or menu into the project.
> 
> Really glad this plugin exists, would love for this to get rolled into Godot 4.3!

@zolrath Okay, I will locate the problem as soon as possible and support the latest version of Godot, thank you for your support ~
If you can, I hope you provide more detailed error information, thank you ~

**Comment by cyraid** [comment]
I don't seem to get notifications of issues Hmm.. cause I fixed it on mine a long time ago but forgot to push the changes! I'll do so very soon, not at PC ATM!

**Comment by xiezi5160** [comment]
> I don't seem to get notifications of issues Hmm.. cause I fixed it on mine a long time ago but forgot to push the changes! I'll do so very soon, not at PC ATM!

@cyraid Great, thank you for sharing a lot with me~

**Comment by xiezi5160** [comment]
@cyraid The new version has been submitted to Asset Library, waiting for review.Thank you for your help~
@zolrath If you need to use it urgently, replace the version 2.0.3 of github into the corresponding folder of the project plug -in, thank you for your support ~
